/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LMS.UI;

import LMS.*;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author itsme
 */
public class AddClerkUI extends javax.swing.JFrame {

    GUIHandler handler;
    boolean isClerk;
    /**
     * Creates new form AddClerkUI
     */
    public AddClerkUI(GUIHandler handler, boolean isClerk) {
        this.handler = handler;
        this.isClerk = isClerk;
        initComponents();
        this.AL.setName("Error");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        HL = new javax.swing.JLabel();
        TL1 = new javax.swing.JLabel();
        TL2 = new javax.swing.JLabel();
        TL3 = new javax.swing.JLabel();
        TL4 = new javax.swing.JLabel();
        TB1 = new javax.swing.JTextField();
        TB2 = new javax.swing.JTextField();
        TB3 = new javax.swing.JTextField();
        TB4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        AL = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1500, 1000));
        setMinimumSize(new java.awt.Dimension(1500, 1000));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        HL.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        HL.setText("Add Clerk");

        TL1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        TL1.setText("Clerk Name:");

        TL2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        TL2.setText("Clerk Address:");

        TL3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        TL3.setText("Clerk Phone:");

        TL4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        TL4.setText("Clerk Salary:");

        TB1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        TB1.setName("ClerkNameTextBox"); // NOI18N
        TB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TB1ActionPerformed(evt);
            }
        });

        TB2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        TB2.setName("ClerkAddressTextBox"); // NOI18N

        TB3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        TB3.setName("ClerkPhoneTextBox"); // NOI18N

        TB4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        TB4.setName("ClerkSalaryTextBox"); // NOI18N

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton1.setText("Add");
        jButton1.setName("AddClerkButton"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        AL.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton2.setText("< Back");
        jButton2.setName("BackButton"); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(430, 430, 430)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(TL4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TB4, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(TL3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TB3, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(TL2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TB2, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(TL1)
                        .addGap(48, 48, 48)
                        .addComponent(TB1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AL)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(700, 700, 700))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 443, Short.MAX_VALUE)
                .addComponent(HL)
                .addGap(647, 647, 647))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(HL))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jButton2)))
                .addGap(113, 113, 113)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(TL1))
                    .addComponent(TB1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(TL2))
                    .addComponent(TB2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TB3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(TL3)
                        .addGap(8, 8, 8)))
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(TL4))
                    .addComponent(TB4, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(88, 88, 88)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(AL)
                .addContainerGap(165, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        if(isClerk){
            HL.setText("Add Clerk");
            TL1.setText("Clerk Name:");
            TL2.setText("Clerk Address:");
            TL3.setText("Clerk Phone:");
            TL4.setText("Clerk Salary:");
        }
        else{
            HL.setText("Add Librarian");
            TL1.setText("Librarian Name:");
            TL2.setText("Librarian Address:");
            TL3.setText("Librarian Phone:");
            TL4.setText("Librarian Salary:");
        }
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            AL.setText("");
            if(!TB1.getText().equals("") && !TB2.getText().equals("") && !TB3.getText().equals("") && !TB4.getText().equals("")){
                if(TB3.getText().matches("[0-9]+")){
                    if(TB4.getText().matches("[0-9]+")){
                        if(TB1.getText().length() <= 40 && TB2.getText().length() <= 60 && TB3.getText().length() <= 30 && TB4.getText().length() <= 10){
                            if(isClerk)
                            {
                                Clerk c = new Clerk(-1, TB1.getText(), TB2.getText(), TB3.getText(), "-1", Integer.parseInt(TB4.getText()),-1);
                                handler.lib.addClerk(c);
                                try {
                                    handler.lib.fillItBack(handler.con);
                                } catch (SQLException ex) {
                                    Logger.getLogger(AddClerkUI.class.getName()).log(Level.SEVERE, null, ex);
                                }
                                AL.setText(TB1.getText() + " as Clerk has been added with ID: " + Integer.toString(c.getID()) + " Password: " + c.getPassword());
                            }
                            else
                            {
                                Librarian l = new Librarian(-1, TB1.getText(), TB2.getText(), TB3.getText(), "-1", Integer.parseInt(TB4.getText()),-1); 
                                if(handler.lib.addLibrarian(l))
                                {
                                    try {
                                        handler.lib.fillItBack(handler.con);
                                    } catch (SQLException ex) {
                                        Logger.getLogger(AddClerkUI.class.getName()).log(Level.SEVERE, null, ex);
                                    }
                                    AL.setText(TB1.getText() + " as Librarian has been added with ID: " + Integer.toString(l.getID()) + " Password: " + l.getPassword());
                                }
                                else{
                                    AL.setText("Library already has one librarian and new Librarian could not be created.");
                                }
                            }
                        }
                        else
                        {
                            AL.setText("Word limit of field(s) exceeded");
                        }
                    }
                    else{
                        AL.setText("Salary can only be number with/without decimals");
                    }
                }
                else{
                    AL.setText("Phone number can only be numbers");
                }
            }
            else{
                AL.setText("Field(s) cannot be empty");
            }
            
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.hide();
        new AdminUI(handler).setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void TB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TB1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TB1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddClerkUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddClerkUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddClerkUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddClerkUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new AddClerkUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AL;
    private javax.swing.JLabel HL;
    private javax.swing.JTextField TB1;
    private javax.swing.JTextField TB2;
    private javax.swing.JTextField TB3;
    private javax.swing.JTextField TB4;
    private javax.swing.JLabel TL1;
    private javax.swing.JLabel TL2;
    private javax.swing.JLabel TL3;
    private javax.swing.JLabel TL4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
