/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LMS.UI;

import LMS.*;

/**
 *
 * @author itsme
 */
public class MainUI extends javax.swing.JFrame {

    /**
     * Creates new form MainUI
     */
    GUIHandler handler;
    public MainUI(GUIHandler handler) {
        this.handler = handler;
        initComponents();
        this.AL.setName("Error");
    }

    public MainUI() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BG = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        LRB = new javax.swing.JRadioButton();
        ALRB = new javax.swing.JRadioButton();
        LUIL = new javax.swing.JLabel();
        LPL = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        AL = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        LUITB = new javax.swing.JPasswordField();
        LPTB = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1500, 1000));
        setSize(new java.awt.Dimension(1500, 1000));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setName("LoginButton"); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel1.setText("WELCOME TO LIBRARY MANAGEMENT SYSTEM");

        LRB.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LRB.setText(" LOGIN");
        LRB.setName("LoginRadioButton"); // NOI18N
        LRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LRBActionPerformed(evt);
            }
        });

        ALRB.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ALRB.setText("ADMIN LOGIN");
        ALRB.setName("MainAdminLoginRadioButton"); // NOI18N
        ALRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ALRBActionPerformed(evt);
            }
        });

        LUIL.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LUIL.setText("USER ID:");

        LPL.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LPL.setText("PASSWORD:");

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton2.setText("Login");
        jButton2.setName("LoginButton"); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        AL.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton1.setText("EXIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        LUITB.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LUITB.setName("LUITB"); // NOI18N

        LPTB.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LPTB.setName("PTB"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(536, 536, 536)
                        .addComponent(AL))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jButton1)
                        .addGap(86, 86, 86)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(413, 413, 413)
                        .addComponent(LRB)
                        .addGap(375, 375, 375)
                        .addComponent(ALRB))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(475, 475, 475)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(LPL)
                                .addGap(50, 50, 50))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(LUIL)
                                .addGap(83, 83, 83)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LUITB, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LPTB, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(675, 675, 675)
                        .addComponent(jButton2)))
                .addContainerGap(251, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jButton1)))
                .addGap(74, 74, 74)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LRB)
                    .addComponent(ALRB))
                .addGap(107, 107, 107)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LUIL)
                    .addComponent(LUITB, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LPL)
                    .addComponent(LPTB, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(103, 103, 103)
                .addComponent(jButton2)
                .addGap(62, 62, 62)
                .addComponent(AL)
                .addContainerGap(346, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        BG.add(LRB);
        BG.add(ALRB);
        LRB.setSelected(true);
        LUITB.setEchoChar((char)0);
        LPTB.setEchoChar('*');
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void LRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LRBActionPerformed
        LPL.setVisible(true);
        LPTB.setVisible(true);
        
        LUITB.setEchoChar((char)0);
        LPTB.setEchoChar('*');
        
        LUIL.setText("USER ID:");
        LPL.setText("PASSWORD:");
        
        LUITB.setText("");
        LPTB.setText("");
    }//GEN-LAST:event_LRBActionPerformed

    private void ALRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ALRBActionPerformed
        LUIL.setText("PASSWORD:");
        LUITB.setText("");
        LUITB.setEchoChar('*');
        
        LPL.setVisible(false);
        LPTB.setVisible(false);
    }//GEN-LAST:event_ALRBActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        AL.setText("");
        if(LRB.isSelected()){
            if(!LUITB.getText().equals("") && !LPTB.getText().equals(""))
            {
                if(LUITB.getText().matches("[0-9]+")){
                    if(LUITB.getText().length() <= 10 && LPTB.getText().length() <= 30){
                        Person person = handler.lib.login(LUITB.getText(), LPTB.getText());
                        if(person != null){
                            if(person.getClass().getSimpleName().equals("Clerk"))
                            {
                                this.hide();
                                new ClerkUI(handler, person).setVisible(true);
                            }
                            else if(person.getClass().getSimpleName().equals("Librarian"))
                            {
                                this.hide();
                                new LibrarianUI(handler, person).setVisible(true);
                            }
                            else
                            {
                                this.hide();
                                new BorrowerUI(handler, person).setVisible(true);
                            }

                        }
                        else{
                            AL.setText("Incorrect User Id or Password");
                        }
                    }
                    else{
                        AL.setText("Word limit of field(s) exceeded");
                    }
                }
                else{
                    AL.setText("ID can only be numbers");
                }
            }
            else
            {
                AL.setText("Field(s) cannot be empty");
            }
        }
        else if(ALRB.isSelected()){
            if(!LUITB.getText().equals("")){
                if(LUITB.getText().length() <= 30){
                    if(LUITB.getText().equals("lib"))
                    {
                        this.hide();
                        new AdminUI(handler).setVisible(true);
                    }
                    else{
                        AL.setText("Incorrect Password");
                    }
                }
                else{
                    AL.setText("Word limit of field(s) exceeded");
                }
            }
            else{
                AL.setText("Field cannot be empty");
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MainUI().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AL;
    private javax.swing.JRadioButton ALRB;
    private javax.swing.ButtonGroup BG;
    private javax.swing.JLabel LPL;
    private javax.swing.JPasswordField LPTB;
    private javax.swing.JRadioButton LRB;
    private javax.swing.JLabel LUIL;
    private javax.swing.JPasswordField LUITB;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
