/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LMS.UI;

import LMS.*;
/**
 *
 * @author itsme
 */
public class TotalFineUI extends javax.swing.JFrame {

    GUIHandler handler;
    Person person;
    /**
     * Creates new form TotalFineUI
     */
    public TotalFineUI(GUIHandler handler, Person person) {
        this.handler = handler;
        this.person = person;
        initComponents();
        this.AL.setName("Error");
        this.AL2.setName("Error1");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        AL = new javax.swing.JLabel();
        BIDTL = new javax.swing.JLabel();
        BIDTB = new javax.swing.JTextField();
        CTFB = new javax.swing.JButton();
        AL2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        PNB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1500, 1000));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel1.setText("TOTAL FINE");

        AL.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        BIDTL.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        BIDTL.setText("BORROWER'S ID:");

        BIDTB.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        BIDTB.setName("BorrowerIDTextBox"); // NOI18N

        CTFB.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        CTFB.setText("COMPUTE TOTAL FINE");
        CTFB.setName("ComputeTotalFineButton"); // NOI18N
        CTFB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CTFBActionPerformed(evt);
            }
        });

        AL2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton1.setText("< BACK");
        jButton1.setName("BackButton"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        PNB.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        PNB.setText("PAID NOW");
        PNB.setName("PaidNowButton"); // NOI18N
        PNB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PNBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jButton1)
                        .addGap(420, 420, 420)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(483, 483, 483)
                        .addComponent(BIDTL)
                        .addGap(46, 46, 46)
                        .addComponent(BIDTB, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(595, 595, 595)
                        .addComponent(CTFB))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(700, 700, 700)
                        .addComponent(AL2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(679, 679, 679)
                        .addComponent(AL))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(654, 654, 654)
                        .addComponent(PNB)))
                .addContainerGap(515, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jButton1)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(BIDTL))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(AL))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BIDTB, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34)
                .addComponent(CTFB)
                .addGap(28, 28, 28)
                .addComponent(PNB)
                .addGap(18, 18, 18)
                .addComponent(AL2)
                .addContainerGap(572, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        AL.setText("");
        AL2.setText("");
        if(person.getClass().getSimpleName().equals("Clerk") || person.getClass().getSimpleName().equals("Librarian")){
           BIDTL.setVisible(true);
           BIDTB.setVisible(true);
           CTFB.setVisible(true);
           PNB.setVisible(true);
        }
        else{
           BIDTL.setVisible(false);
           BIDTB.setVisible(false);
           CTFB.setVisible(false);
           PNB.setVisible(false);
           AL.setText("Your total fine is: " + Integer.toString((int)handler.lib.computeFine2((Borrower) person)));
        }
    }//GEN-LAST:event_formWindowOpened

    private void CTFBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CTFBActionPerformed
        AL2.setText("");
        if(!BIDTB.getText().equals("")){
            if(!BIDTB.getText().matches(".*[a-zA-Z]+.*")){
                Borrower br = handler.lib.findBorrower(Integer.parseInt(BIDTB.getText()));
                if(br != null){
                    AL.setText("Your total fine is: " + Integer.toString((int)handler.lib.computeFine2(br)));
                }
                else{
                    AL2.setText("Invalid borrower id");
                }
            }
            else{
                AL2.setText("ID can only be numbers");
            }
        }
        else{
            AL2.setText("Field(s) cannot be empty");
        }
    }//GEN-LAST:event_CTFBActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                                                 
        if(person.getClass().getSimpleName().equals("Librarian")){
            this.hide();
            new LibrarianUI(handler, person).setVisible(true);
        }
        else if(person.getClass().getSimpleName().equals("Clerk")){
            this.hide();
            new ClerkUI(handler, person).setVisible(true);
        }
        else{
            this.hide();
            new BorrowerUI(handler, person).setVisible(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void PNBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PNBActionPerformed
        AL2.setText("");
        Borrower br;
        if(!BIDTB.getText().equals("")){
            if(!BIDTB.getText().matches(".*[a-zA-Z]+.*")){
                br = handler.lib.findBorrower(Integer.parseInt(BIDTB.getText()));
                if(br != null){                    
                    for (int i = 0; i < handler.lib.getLoans().size(); i++)
                    {
                        Loan l = handler.lib.getLoans().get(i);

                        if ((l.getBorrower() == br))
                        {
                            l.payFine();
                        }
                    }
                    AL.setText("Your total fine is now 0");
                }
                else{
                    AL2.setText("Invalid borrower id");
                }
            }
            else{
                AL2.setText("ID can only be numbers");
            }
        }
        else{
            AL2.setText("Field(s) cannot be empty");
        }
        
    }//GEN-LAST:event_PNBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TotalFineUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TotalFineUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TotalFineUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TotalFineUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new TotalFineUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AL;
    private javax.swing.JLabel AL2;
    private javax.swing.JTextField BIDTB;
    private javax.swing.JLabel BIDTL;
    private javax.swing.JButton CTFB;
    private javax.swing.JButton PNB;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
